- hosts: localhost
  connection: local
  gather_facts: true
  vars:
    awsaccess: "{{ lookup('env','awsaccess') }}"
    awssecret: "{{ lookup('env','awssecret') }}"
    
  tasks:
    - name: create instance
      ec2:
        state: present
        #aws_access_key: "{{ awsaccess }}"
        #aws_secret_key: "{{ awssecret }}"
        key_name: some-key
        aws_region: us-east-1
        instance_type: t2.micro
        image: ami-0922553b7b0369273 #amazon linux ami
        group_id: sg-12345678
        count: 1
        vpc_subnet_id: subnet-12345678
        assign_public_ip: yes
        instance_initiated_shutdown_behavior: stop
